# SITE CONFIGURATION
baseurl: "/SDS325H_Spring2015/" # the subpath of your site, e.g. /blog/
url: "http://jgscott.github.io" # the base hostname & protocol for your site
BASE_PATH: /SDS325H_Spring2015

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: SDS 325H (Spring 2015)
  avatar: avatar.png
  gravatar: # email md5 hash
  description: "SDS 325H: Honors Statistics at UT-Austin." # used by search engines
  
  # Header and footer text
  header_text: >
     <p>SDS 325H (Honors Statistics)  •  Spring 2015  •  MW 11:00 - 12:30, FAC 101B
     <br>
     Instructor: James Scott (james.scott@mccombs.utexas.edu)</p>

  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type.html">Type Theme</a>
  
  # Icons
  rss: false
  email_address: "james.scott@mccombs.utexas.edu"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "jgscott/SDS325H_Spring2015"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed